portainer:
  labels:
    io.rancher.sidekicks: ui
    io.rancher.container.create_agent: true
    io.rancher.container.agent.role: environment
  image: ibuildthecloud/portainer-agent:dev
  volumes:
  - /config

ui:
  image: portainer/portainer:pr572
  command: --no-auth --external-endpoints=/config/config.json --sync-interval=5s -p :80
  volumes_from:
  - portainer
  net: container:portainer
